// Demonstration for using the DataFrames API on project RDDs.
p = lynx.newProject('df-test')
p.exampleGraph()
p.df.show()
p.df.groupBy('gender').count().show()
p.df.registerTempTable('example')
df = lynx.sql('select * from example where gender = "Male"')
df.show()
df.printSchema()
df.write().format('com.databricks.spark.csv').option('header', 'true').save('males.csv')
df.write().format('parquet').save('males.parquet')
df.write().format('json').save('males.json')
