# The full list of Conda dependencies for building and running LynxKite.
# For a more limited list please see conda-env.sh.
channels:
- rapidsai
- pyg
- nvidia
- pytorch
- conda-forge
- r
dependencies:
- zip
- unzip
- make
- wget
# For LynxKite backend.
- sbt
- openjdk==11.0.15
- pyspark==3.3.0
# For LynxKite frontend.
- nodejs
- yarn
# For Sphynx.
- go
# For NetworKit.
- compilers
- swig
- libstdcxx-ng
- libnetworkit==10.0
- libtlx==0.5.20200222
# For Python and ML.
- python>=3.8
- numpy
- pandas
- scikit-learn
- pyarrow
- cudatoolkit==11.3.1
- cugraph
- pytorch::pytorch==1.11.0=*cuda*
- pyg==2.0.4=*cu113*
- matplotlib
# PyG dependencies get confused under Mamba.
- pytorch-cluster=*=*cu113*
- pytorch-scatter=*=*cu113*
- pytorch-sparse=*=*cu113*
- pytorch-spline-conv=*=*cu113*
# For Python API and tools.
- autopep8
- mypy
- ruamel.yaml
- requests
- typed-ast
- types-requests
# For R API and tools.
- r
- r-essentials
- r-arrow
