# Install this before running "make":
#
#   conda update env -f conda-env.yml
#
# If you add something that is a runtime dependency too,
# don't forget to update tools/runtime-env.yml.
channels:
- conda-forge
- pytorch
- pyg
dependencies:
- unzip
- make
# For LynxKite backend.
- sbt
# For LynxKite frontend.
- nodejs
- yarn
# For Sphynx.
- go
# For NetworKit.
- compilers
- swig
- libstdcxx-ng
- libnetworkit==10.0
- libtlx==0.5.20200222
# For Python and ML.
- python>=3.8
- numpy
- pandas
- scikit-learn
- pyarrow
- pytorch::pytorch==1.9.1
- pytorch::cpuonly
- pyg==2.0.3
# For Python API and tools.
- autopep8
- mypy
- ruamel.yaml
- requests
- typed-ast
- types-requests
# For Python tests.
- pyspark==3.2.1
