# The full list of Conda dependencies for building and running LynxKite.
# For a more limited list please see conda-env.sh.
channels:
- conda-forge
- r
dependencies:
- zip
- unzip
- make
- wget
# For LynxKite backend.
- sbt
- openjdk==11.0.15
- pyspark==3.3.2
# For LynxKite frontend.
- nodejs
# For Sphynx.
- _go_select>=2.3.0
- go
# For NetworKit.
- compilers
- swig
- libstdcxx-ng
- libnetworkit==10.0
- libtlx==0.5.20200222
# For ML.
- python==3.10.*
# For R API and tools.
- r
- r-essentials
- r-arrow=
- r-htmlwidgets
- r-openssl
- r-plotly
