### Add popularity x similarity optimized edges

<<experimental-operation,+++<i class="fa fa-warning"></i>+++ *Warning! Experimental operation.*>>

Creates a graph with given amount of vertices and average degrees. The edges
will follow a power-law - also known as scale-free - distribution and have
high clustering. Vertices get two edge attributes called "radial" and
"angular" that can later be used for edge strength evaluation or link prediction.
Algorithm based on https://arxiv.org/abs/1106.0286[paper 1] and
https://www.caida.org/publications/papers/2015/network_mapping_replaying_hyperbolic/network_mapping_replaying_hyperbolic.pdf[paper 2]

The edges are generated by simulating hyperbolic growth. Vertices are added
one by one and at the time of each addition new edges are created in two ways.
First, the new vertex is added and it creates edges from itself to older vertices
 - "external" edges. Then some new edges are added between older vertices
 - "internal" edges.
This way the average amount of edges added per vertex will be slightly more than
 _externalDegree + internalDegree_.

====
[[externaldegree]] External degree::
The number of edges a vertex creates from itself upon addition to the growing graph.

[[internaldegree]] Internal degree::
The average number of edges created between older vertices whenever a new vertex
 is added to the growing graph.

[[exponent]] Exponent::
The exponent of the power-law degree distribution. Values can be 0.5 - 1, endpoints excluded.

[[seed]] Seed::
The random seed.
+
include::{g}[tag=random-seed]
====
