### Bundle vertex attributes into a Vector

Bundles the chosen `number` and `Vector[number]` attributes into one `Vector` attribute.
By default, LynxKite puts the numeric attributes after each other in alphabetical order and
then concatenates the Vector attributes to the resulting Vector in alphabetical
order as well. The resulting attribute is undefined where any of the input attributes
is undefined.

For example, if you bundle the `age`, `favorite_day` and `income` attributes into a `Vector` attribute
called `everything`, you end up with the following attributes.

|===
| name | age | income | favorite_day | everything

| Adam | 20.3 | 1000 | Vector(12, 24) | Vector(20.3, 1000, 12, 24)
| Eve | 18.2 | _undefined_ | Vector(12, 24) | _undefined_
| Bob | 50.3 | 2000 | Vector(9, 17) | Vector(50.3, 2000, 9, 17)
| Isolated Joe | 2.0 | _undefined_ | Vector(3, 19) | _undefined_
|===

====
*Parameters*

[p-output]#Save as#::
The new attribute will be created under this name.

[p-elements]#Elements#::
The attributes you would like to bundle into a Vector.
====
