### Compare segmentation edges

Compares the edge sets of two segmentations and computes _precision_ and _recall_.
In order to make this work, the edges of the both segmentation graphs should be
matchable against each other. Therefore, this operation only allows comparing
segmentations which were created using the <<Use base project as segmentation>> operation
from the same project. (More precisely, a one to one correspondence is needed between
the vertices of both segmentations and the base project.)

You can use this operation for example to evaluate different colocation results against
a reference result.

====
One of the input segmentations is the _golden_ (or reference) graph, against which the
other one, the _test_ will be evaluated. The precision and recall values
are computed the following way:

_numGoldenEdges := number of edges in the golden segmentation graph_ +
_numTestEdges := number of edges in the test segmentation graph_ +
_numCommonEdges := number of common edges in the two segmentation graphs_ +
_precision := numCommonEdges / numTestEdges_ +
_recall := numCommonEdges / numGoldenEdges_

The results will be created as scalars in the test segmentaion. Parallel edges
are treated as one edge. Also, for each matching edge an edge attribute is
created in both segmentation graphs.

[[golden]] Golden segmentation::
Segmentation containing the golden edges.

[[test]] Test segmentation::
Segmentation containing the test edges.

====
