### Compute PageRank

Calculates http://en.wikipedia.org/wiki/PageRank[PageRank] for every vertex.
PageRank is calculated by simulating random walks on the graph. Its PageRank
reflects the likelihood that the walk leads to a specific vertex.

Let's imagine a social graph with information flowing along the edges. In this case high
PageRank means that the vertex is more likely to be the target of the information.

Similarly, it may be useful to identify information sources in the reversed graph.
Simply reverse the edges before running the operation to calculate the reverse PageRank.

include::{g}[tag=cugraph]

====
[p-name]#Attribute name#::
The new attribute will be created under this name.

[p-weights]#Weight attribute#::
The edge weights. Edges with greater weight correspond to higher probabilities
in the theoretical random walk.

[p-iterations]#Number of iterations#::
PageRank is an iterative algorithm. More iterations take more time but can lead
to more precise results. As a rule of thumb set the number of iterations to the
diameter of the graph, or to the median shortest path.

[p-damping]#Damping factor#::
The probability of continuing the random walk at each step. Higher damping
factors lead to longer random walks.

[p-direction]#Direction#::
 - `incoming edges`: Simulate random walk in the reverse edge direction.
   Finds the most influential sources.
 - `outgoing edges`: Simulate random walk in the original edge direction.
   Finds the most popular destinations.
 - `all edges`: Simulate random walk in both directions.
====
