### Compute distance via shortest path

Calculates the length of the shortest path from a given set of vertices for every vertex.
To use this operation, a set of starting _v~i~_ vertices has to be specified, each with
a starting distance _sd(v~i~)_. Edges represent a unit distance by default, but this
can be overridden using an attribute. This operation will compute for each vertex
_v~i~_ the smallest distance from a starting vertex, also counting the starting
distance of the starting vertex: _d(v~i~) = min~j~(sd(v~j~) + D(s~j~, v~i~, I))_ where
_D(x, y, I)_ is the length of the shortest path between _x_ and _y_ using at most _I_
edges.

For example, vertices can be cities and edges can be flights with a given
cost between the cities. Given a set of starting cities, which might as well be
only one city, this operation can compute the lowest cost for reaching each
city with a given maximum number of flight changes. In addition
to that, an optional base cost can be specified for each starting city, which will
be counted into each path starting from that city. For example, that could be the
price of getting to the given city by train.

If a city can be reached from more than one of the starting cities, then still only
one cost value is computed: the one from the starting city where the route has the
lowest cost. If a starting city can be reached from another starting city in a
cheaper way than the starting cost, then the assigned cost of that city will be
the cheaper cost.

====
[[name]] Attribute name::
The new attribute will be created under this name.

[[edge_distance]] Edge distance attribute::
The attribute containing the distances corresponding to edges. (Cost in the above example.)

Negative values are allowed but there must be no loops where the sum of
distances is negative.

[[starting_distance]] Starting distance attribute::
A numeric attribute that specifies the initial distances of the vertices that we
consider already reachable before starting this operation. (In the above example,
specify this for the elements of the starting set, and leave this undefined for
the rest of the vertices.)

[[iterations]] Maximum number of iterations::
The maximum number of edges considered for a shortest-distance path.

====
