### Derive vertex attribute

Generates a new attribute based on existing vertex attributes. The value expression can be
an arbitrary JavaScript expression, and it can refer to existing attributes as if they
were local variables.

For example you can write `age * 2` to generate a new attribute
that is the double of the _age_ attribute. Or you can write
`gender == 'Male' ? 'Mr ' + name : 'Ms ' + name` for a more complex example.
For more details see <<javascript-guide>>.

You can also refer to graph attributes (aka scalars) in the JS expression. For example,
assuming that you have a graph attribute _income_average_,
you can use the expression `income > income_average ? 1.0 : 0.0` to
identify people whose income is above average.

JavaScript arrays like `[1, 2, 3]` are automatically converted back to vectors (if the result type
is set accordingly). Vectors can not contain `undefined` elements.

====
[[output]] Save as::
The new attribute will be created under this name.

[[type]] Result type::
The type (`Double`, `String`, `Vector of Doubles` or `Vector of Strings`) of the created attribute.

[[defined_attrs]] Only run on defined attributes::
- `true`: The new attribute will only be defined on vertices for which all the attributes used in the
  expression are defined.
- `false`: The new attribute is defined on all vertices. In this case the JavaScript expression needs
  to be prepared to handle undefined input attribute values.

[[expr]] Value::
The JavaScript expression. You can enter multiple lines in the editor.
====
