### Derived vertex attribute

Generates a new attribute based on existing vertex attributes. The value expression can be
an arbitrary JavaScript expression, and it can refer to existing attributes as if they
were local variables. The new attribute will only be defined on vertices for which all the
attributes used in the expression are defined.

For example you can write `age * 2` to generate a new attribute
that is the double of the _age_ attribute. Or you can write
`gender == 'Male' ? 'Mr ' + name : 'Ms ' + name` for a more complex example.
For more details see <<javascript-guide>>.

You can also refer to graph attributes (aka scalars) in the JS expression. For example,
assuming that you have a graph attribute _income_average_,
you can use the expression `income > income_average ? 1.0 : 0.0` to
identify people whose income is above average.

====
[[output]] Save as::
The new attribute will be created under this name.

[[type]] Result type::
The type (`Double` or `String`) of the created attribute.

[[expr]] Value::
The JavaScript expression.
====
