### Export to CSV

CSV stands for comma-separated values. It is a common human-readable file format where each record
is on a separate line and fields of the record are simply separated with a comma or other delimiter.
CSV does not store data types, so all fields become strings when importing from this format.

====
[[path]] Path::
The distributed file-system path of the output file. It defaults to `<auto>`, in which case the
path is auto generated from the parameters and the type of export (e.g. `Export to CSV`).
This means that the same export operation with the same parameters always generates the same path.

[[delimiter]] Delimiter::
The delimiter separating the fields in each line.

[[quote]] Quote::
The character used for quoting strings that contain the delimiter. If the string also contains the
quote character, it will be escaped with a backslash (`{backslash}`).

[[header]] Include header::
Whether or not to include the header in the CSV file. If the data is exported as multiple CSV files
the header will be included in each of them. When such a data set is directly downloaded, the header
will appear multiple times in the resulting file.

[[version]] Version::
Version is the version number of the result of the export operation. It is a non negative integer.
LynxKite treats export operations as other operations: it remembers the result (which in this case
is the knowledge that the export was successfully done) and won't repeat the calculation. However,
there might be a need to export an already exported table with the same set of parameters (e.g. the
exported file is lost). In this case you need to change the version number, making that parameters
are not the same as in the previous export.
====
