### Export to Hive

Export a table directly to https://hive.apache.org/[Apache Hive].

====

[p-table]#Table#::
The name of the database table to export to.

[p-mode]#Mode#::
Describes whether LynxKite should expect a table to already exist and how to handle this case.
+
**The table must not exist** means the table will be created and it is an error if it already
exists.
+
**Drop the table if it already exists** means the table will be deleted and re-created if
it already exists. Use this mode with great care. This method cannot be used if you specify
any fields to partition by, the reason being that the underlying Spark library will delete
all other partitions in the table in this case.

+
**Insert into an existing table** requires the
table to already exist and it will add the exported data at the end of the existing table.

[p-partition_by]#Partition by#::
The list of column names (if any) which you wish the table to be partitioned by. This cannot
be used in conjunction with the "Drop the table if it already exists" mode.

====
