### Export to CSV

CSV stands for comma-separated values. It is a common human-readable file format where each record
is on a separate line and fields of the record are simply separated with a comma or other delimiter.
CSV does not store data types, so all fields become strings when importing from this format.

====
[[path]] Path::
The distributed file-system path of the output file. It defaults to `<download>`, in which case the
output file will be downloaded through the browser. This is the simplest option for small data sets.

[[delimiter]] Delimiter::
The delimiter separating the fields in each line.

[[quote]] Quote::
The character used for quoting strings that contain the delimiter. If the string also contains the
quote character, it will be escaped with a backslash (`{backslash}`).

[[header]] Include header::
Whether or not to include the header in the CSV file. If the data is exported as multiple CSV files
the header will be included in each of them. When such a data set is directly downloaded, the header
will appear multiple times in the resulting file.
====
