### Export to AVRO 

https://avro.apache.org/[Apache AVRO] is a row-oriented remote procedure call and data serialization framework. 

====
[p-path]#Path#::
The distributed file-system path of the output file. It defaults to `<auto>`, in which case the
path is auto generated from the parameters and the type of export (e.g. `Export to CSV`).
This means that the same export operation with the same parameters always generates the same path.

[p-version]#Version#::
Version is the version number of the result of the export operation. It is a non negative integer.
LynxKite treats export operations as other operations: it remembers the result (which in this case
is the knowledge that the export was successfully done) and won't repeat the calculation. However,
there might be a need to export an already exported table with the same set of parameters (e.g. the
exported file is lost). In this case you need to change the version number, making that parameters
are not the same as in the previous export.

[p-for_download]#Export for download#::
Set this to "true" if the purpose of this export is file download: in this case LynxKite will
repartition the data into one single file, which will be downloaded. The default "no" will
result in no such repartition: this performs much better when other, partition-aware tools
are used to import the exported data.

include::{g}[tag=save-mode-options]
====
