### Export graph to Neo4j

Exports a graph from LynxKite to https://neo4j.com/[Neo4j].
The whole graph will be copied to Neo4j with all attributes.
No existing data is modified in Neo4j.

A `!LynxKite export timestamp` property is added to each new
node and relationship in Neo4j. This helps clean up the export if needed.

The Cypher query to export nodes is, depending on whether an attribute specifies the node labels:

    UNWIND $events AS event
    // Without node labels:
    CREATE (n)
    SET n += event
    // With node labels taken from the "label" attribute:
    CALL apoc.create.node(split(event.`label`, ','), event) YIELD node
    RETURN 1

The Cypher query to export relationships is, depending on whether an attribute specifies the
relationship types:

    UNWIND $events AS event
    MATCH (src {`!LynxKite ID`: event.`!Source LynxKite ID`}), (dst {`!LynxKite ID`: event.`Destination LynxKite ID`})
    // Without relationship types:
    CREATE (src)-[r:EDGE]->(dst)
    SET r += event
    // With relationship types taken from the "type" attribute:
    CALL apoc.create.relationship(src, event.`type`, event, dst) YIELD rel
    RETURN 1

====

[p-url]#Neo4j connection#::
The Neo4j connection string of the form `bolt://localhost:7687`.

[p-username]#Neo4j username#::
Username for the connection.

[p-password]#Neo4j password#::
Password for the connection. It will be saved in the workspace and visible to anyone with
access to the workspace.

[p-database]#Neo4j database#::
If the Neo4j server has multiple databases, you can specify which one to write to.

[p-version]#Export repetition ID#::
LynxKite only re-computes outputs if parameters or inputs have changed.
This is true for exports too. If you want to repeat a previous export, you can increase this
export repetition ID parameter.

[p-node_labels]#Node labels#::
A string vertex attribute that is a comma-separated list of labels to apply to the newly
created nodes. Optional. You must have https://neo4j.com/developer/neo4j-apoc/[Neo4j APOC]
installed on the Neo4j instance to use this.

[p-relationship_type]#Attribute with relationship type#::
A string edge attribute that specifies the relationship type for each newly created relationship.
Optional. You must have https://neo4j.com/developer/neo4j-apoc/[Neo4j APOC]
installed on the Neo4j instance to use this.

====
