### Export segmentation to file

Writes a segmentation to a text file.
The first two columns of the file will contain the base vertex and segment IDs.

include::{g}[tag=file-export]

====
[[path]] Destination path::
The file to write to. Must use <<prefixed-paths>>.

[[link]] Download link name::
A new scalar will be created under this name. You can download the exported file through this link.

[[base_id_attr]] Project vertex id attribute::
The attribute that identifies the source vertices (the vertices in the project that are connected to
the segmentations) in the output. By default, this will be the internal vertex ID
(which is guaranteed to be unique). However, you might find it more convenient to use some
other vertex attribute, e.g., a phone number.

[[seg_id_attr]] Segmentation vertex id attribute::
The attribute that identifies the destination vertices (the segmentation vertices) in the output.
By default, this will be the internal vertex ID (which is guaranteed to be unique).
However, you might find it more convenient to use some other segmentation vertex attribute,
e.g., a city name.

[[format]] File format::
Only CSV (comma-separated values) is currently supported.
====
