### Export to CSV

CSV stands for comma-separated values. It is a common human-readable file format where each record
is on a separate line and fields of the record are simply separated with a comma or other delimiter.
CSV does not store data types, so all fields become strings when importing from this format.

====
[p-path]#Path#::
The distributed file-system path of the output file. It defaults to `<auto>`, in which case the
path is auto generated from the parameters and the type of export (e.g. `Export to CSV`).
This means that the same export operation with the same parameters always generates the same path.

[p-delimiter]#Delimiter#::
The delimiter separating the fields in each line.

[p-quote]#Quote#::
The character used for quoting strings that contain the delimiter. If the string also contains the
quote character, it will be escaped with a backslash (`{backslash}`).

[p-quote_all]#Quote all strings#::
Quotes all string values if set. Only quotes in the necessary cases otherwise. 

[p-header]#Include header#::
Whether or not to include the header in the CSV file. If the data is exported as multiple CSV files
the header will be included in each of them. When such a data set is directly downloaded, the header
will appear multiple times in the resulting file.

[p-escape]#Escape character#::
The character used for escaping quotes inside an already quoted value.

[p-null_value]#Null value#::
The string representation of a `null` value. This is how `null`-s are going to be written in
the CSV file.

[p-date_format]#Date format#::
The string that indicates a date format. Custom date formats follow the formats at
https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html[java.text.SimpleDateFormat].

[p-timestamp_format]#Timestamp format#::
The string that indicates a timestamp format. Custom date formats follow the formats at
https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html[java.text.SimpleDateFormat].

[p-drop_leading_white_space]#Drop leading white space#::
A flag indicating whether or not leading whitespaces from values being written should be skipped.

[p-drop_trailing_white_space]#Drop trailing white space#::
A flag indicating whether or not trailing whitespaces from values being written should be skipped.

[p-version]#Version#::
Version is the version number of the result of the export operation. It is a non negative integer.
LynxKite treats export operations as other operations: it remembers the result (which in this case
is the knowledge that the export was successfully done) and won't repeat the calculation. However,
there might be a need to export an already exported table with the same set of parameters (e.g. the
exported file is lost). In this case you need to change the version number, making that parameters
are not the same as in the previous export.
====
