## Find infocom communities

Creates a segmentation of overlapping communities.

The algorithm finds maximal cliques then merges them to communities.
Two cliques are merged if they sufficiently overlap.
More details can be found in
http://www.insead.edu/facultyresearch/research/details_papers.cfm?id=24896[
Information Communities: The Network Structure of Communication].

====
[[cliques_name]] Name for maximal cliques segmentation::
A new segmentation with the maximal cliques will be saved under this name.

[[communities_name]] Name for communities segmentation::
The new segmentation with the infocom communities will be saved under this name.

[[bothdir]] Edges required in both directions::
Whether edges have to exist in both directions between all members of a clique.
+
=====
If the direction of the edges is not important, set this to `false`. This will allow placing two
vertices into the same clique even if they are only connected in one direction.
=====

[[min]] Minimum clique size::
Cliques smaller than this will not be collected.
+
This improves the performance of the algorithm, and small cliques are often not a good indicator
anyway.

[[adjacency_threshold]] Adjacency threshold for clique overlaps::
Clique overlap is a measure of the overlap between two cliques relative to their sizes.
It is normalized to [0.0, 1.0). This parameter controls when to merge cliques into a community.
====
