### Find infocom communities

Creates a segmentation of overlapping communities.

The algorithm finds maximal cliques then merges them to communities.
Two cliques are merged if they sufficiently overlap.
More details can be found in
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1753903[
Information Communities: The Network Structure of Communication].

It often makes sense to filter out high degree vertices before detecting
communities. In a social graph real people are unlikely to maintain thousands of
connections. Filtering high degree vertices out is also known to speed up the
algorithm significantly.

====
[p-cliques_name]#Name for maximal cliques segmentation#::
A new segmentation with the maximal cliques will be saved under this name.

[p-communities_name]#Name for communities segmentation#::
The new segmentation with the infocom communities will be saved under this name.

[p-bothdir]#Edges required in both directions#::
Whether edges have to exist in both directions between all members of a clique.
+
=====
If the direction of the edges is not important, set this to `false`. This will
allow placing two vertices into the same clique even if they are only connected
in one direction.
=====

[p-min]#Minimum clique size#::
Cliques smaller than this will not be collected.
+
This improves the performance of the algorithm, and small cliques are often not
a good indicator anyway.

[p-adjacency_threshold]#Adjacency threshold for clique overlaps#::
Clique overlap is a measure of the overlap between two cliques relative to
their sizes. It is normalized to [0, 1). This parameter controls when to merge
cliques into a community.
+
A lower threshold results in fewer, larger communities. If the threshold is low
enough, a single giant community may emerge. Conversely, increasing the threshold
eventually makes the giant community disassemble.
====
