### Import vertex attributes

Imports vertex attributes for existing vertices from a table. This is
useful when you already have vertices and just want to import one or more attributes.

There are two different use cases for this operation:
- Import using unique vertex attribute values. For example if the vertices represent people
this attribute can be a personal ID. In this case the operation fails in case of duplicate
attribute values (either among vertices or in the table).
- Import using a normal vertex attribute. For example this can be a city of residence (vertices
are people) and we can import census data for those cities for each person. Here the operation
allows duplications of cities among vertices (but not in the lookup table).

====
include::{g}[tag=table-import]

[[id_attr]] Vertex attribute::
The vertex attribute which is used to join with the table's ID column.

[[id_column]] ID column::
The ID column name in the table. This should be a String column that uses the values
of the chosen vertex attribute as IDs.

[[prefix]] Name prefix for the imported vertex attributes::
Prepend this prefix string to the new vertex attribute names. This can be used to avoid
accidentally overwriting existing attributes.

[[unique_keys]] Assert unique vertex attribute values::
Assert that the vertex attribute values have to be unique if set true. The values of the
matching ID column in the table have to be unique in both cases.
====
