### Import vertex attributes

Imports vertex attributes for existing vertices from a table. This is
useful when you already have vertices and just want to import one or more attributes.

There are two different use cases for this operation:
- Import using unique vertex attribute values. For example if the vertices represent people
this attribute can be a personal ID. In this case the operation fails in case of duplicate
attribute values.
- Import using a normal vertex attribute. For example in the above case this can be a city
of residence and we can import census data for those cities for each people. Here the operation
allows duplications (but not in the lookup table).

====
include::{g}[tag=table-import]

[[id-attr]] Vertex ID attribute::
The vertex attribute which is used in the table's ID column.

[[id-column]] ID column::
The ID column name in the table. This should be a string column that uses the same IDs as
the chosen vertex ID attribute.

[[prefix]] Name prefix for the imported vertex attributes::
Prepend this prefix string to the new vertex attribute names. This can be used to avoid
accidentally overwriting existing attributes.

[[unique-keys]] Assert unique vertex ID attribute values::
Assert that the vertex ID attribute values have to be unique if set true. The values of the
matching ID column in the table have to be unique in both cases.
====
