### Lookup region

For every `position` vertex attribute looks up features in a Shapefile and returns a specified
attribute.

* The lookup is based on the
  http://support.esri.com/other-resources/gis-dictionary/term/envelope[bounding boxes] of the
  feature. The bounding box depends on the coordinate reference system of the feature too.
* If there are no matching features the output is omitted.
* If the specified attribute does not exist for any matching feature the output is omitted.
* If there are multiple suitable features the algorithm picks the first one.

A default world country borders dataset is included from
http://thematicmapping.org/downloads/world_borders.php.

====

*Parameters*

[[position]] Position::
The (latitude, longitude) location tuple.

[[shapefile]] Shapefile::
The https://en.wikipedia.org/wiki/Shapefile[Shapefile] used for the lookup. The list is created from
the `.shp` files in the `KITE_META/resources/shapefiles` directory.

[[attribute]] Attribute from the Shapefile::
The attribute in the Shapefile used for the output.

[[output]] Output::
The name of the new vertex attribute.
====
