### Map hyperbolic coordinates

Map an undirected graph to a hyperbolic surface. Vertices get two edge attributes called
"radial" and "angular" that can be used for edge strength evaluation or link prediction.
Algorithm based on https://www.caida.org/publications/papers/2015/network_mapping_replaying_hyperbolic/network_mapping_replaying_hyperbolic.pdf[paper].

The coordinates are generated by simulating hyperbolic growth. The algorithm's results
are most useful when the graph to be mapped follows a power-law degree distribution
and has high clustering.

====
[[avgexpecteddegree]] Average expected degree::
The number of edges a vertex creates from itself upon addition to simulated growing
graph. If unknown, use the _average degree_ or _minimum vertex degree_.

[[exponent]] Exponent::
The exponent of the power-law degree distribution. Values can be 0.5 - 1, endpoints excluded.

[[temperature]] Temperature::
How much clustering is considered during the algorithm.
Values can be (0<) - infinity. 
Clustering is strongest when approaching 0. Clustering approaches 0 at values 1 and above.

[[seed]] Seed::
The random seed.
+
include::{g}[tag=random-seed]
====
