### Mask vertex attribute

Uses the https://en.wikipedia.org/wiki/PBKDF2[PBDKF2] algorithm to mask an attribute: all values of the attribute
 get replaced by a seemingly random value. The same original values get replaced by the same new value and
different original values get (almost certainly) replaced by different new values.

As all operations, this one also can be undone in the project so it would only provide real masking if the data is
exported outside of the project.

Treat the salt like a password for the data. Choose a long string that the recipient of the data has no chance of
guessing. (Do not use the name of a person or project.)

To illustrate the mechanics of irreversible masking and the importance of a good salt string, consider the following
example. We have a data set of phone calls and we have masked the phone numbers. Arthur gets access to the masked data
and learns or guesses the salt. Arthur can now apply the same masking to the phone number of Guinevere as was used on
the original data set and look her up in the graph. He can also apply masking to the phone numbers of all the knights
of the round table and see which knight has Guinevere been making calls to.

====
[[attr]] Vertex attribute::
The attribute(s) which will be masked.

[[salt]] Salt::
The value of the salt.
====
