### Predict edges with hyperbolic positions
<<experimental-operation,+++<i class="fa fa-warning"></i>+++ *Warning! Experimental operation.*>>

Creates additional edges in a graph based on
hyperbolic distances between vertices.
 _2 * size_ edges will be added because
the new edges are undirected.
Vertices must have two _number_ vertex attributes to be
used as radial and angular coordinates.

====
[p-size]#Number of predictions#::
The number of edges to generate.
The total number will be _2 * size_ because every
edge is added in two directions.

[p-externaldegree]#External degree#::
The number of edges a vertex creates from itself
 upon addition to the growth simulation graph.

[p-internaldegree]#Internal degree#::
The average number of edges created between older vertices whenever
a new vertex is added to the growth simulation graph.

[p-exponent]#Exponent#::
The exponent of the power-law degree distribution.
Values can be 0.5 - 1, endpoints excluded.

[p-radial]#Radial#::
The vertex attribute to be used as radial coordinates.
Should not contain negative values.

[p-angular]#Angular#::
The vertex attribute to be used as angular coordinates.
Values should be 0 - 2 * Pi.
====
