### Random walk sample

This operation creates a small smart sample of a graph. First, a random vertex is chosen
for start point. From this point a random walk is performed until the requested number of unique vertices are
visited. At every step the walker jumps back to the start point and starts a new walk with some probability.
If the walker can not visit enough unique vertices a new start point is selected. In case the sample size
is still not big enough after several tries, the walk is aborted and the nodes visited so far are considered
as the final sample.

The result of the operation is a subgraph of the original graph consisting of the vertices the walker visited
and edges the walker used for transition. This operation also creates two new zero-one attributes that can be used to
manually produce the subgraph by filtering.

For example, you can create a random sample of the project's graph to test your model on smaller data set.

====
[[samplesize]] Sample size::
The (maximum) number of vertices in the sample.

[[restartprobability]] Restart probability::
The probability of starting a new walk instead of walking.

[[startpoints]] Number of starting points::
The limit of how many times a new start point can be selected. With low values, long run times can be
avoided at the cost of possibly returning a sample of size smaller than requested.

[[vertexattrname]] Save vertex selection as::
The name of the attribute which shows which vertices belong to the sample. A value of 1.0 indicates that
the vertex is part of the sample, otherwise the value is set to 0.0. The attribute is not added to
the project if the name is an emtpy string.

[[edgeattrname]] Save edge selection as::
The name of the attribute which shows which edges belong to the sample. A value of 1.0 indicates that
the edge is part of the sample, otherwise the value is set to 0.0. The attribute is not added to
the project if the name is an emtpy string.

[[automaticfilter]] Filter graph automatically::
Whether to perform the filtering as part of this operation or create only the attributes and leave the graph
otherwise unmodified. Either attribute names have to be provided or this has to be set true.

[[seed]] Seed::
The random seed.
+
include::{g}[tag=random-seed]
====