### Sample graph by random walks

This operation realizes a random walk on the graph which can be used as a small smart sample to
test your model on. The walk starts from a randomly selected vertex and at every step either aborts
the current walk (with probability _Walk abortion probability_) and jumps back to the start point
or moves to a randomly selected (directed sense) neighbor of the current vertex. After _Number of
walks from each start point_ restarts it selects a new start vertex. After _Number of start points_
new start points were selected, it stops. The performance of this algorithm according to different
metrics can be found in the following publication,
https://cs.stanford.edu/people/jure/pubs/sampling-kdd06.pdf.

The output of the operation is a vertex and an edge attribute which describes which was the first
step that ended at the given vertex / traversed the given edge. The attributes are not defined on
vertices that were never reached or edges that were never traversed.

If the resulting sample is still too large, it can be quickly reduced by keeping only the low index
nodes and edges. Obtaining a sample with exactly `n` vertices is also possible with the
following procedure.

. Run this operation. Let us denote the computed vertex attribute by `first_reached` and edge
attribute by `first_traversed`.
. Rank the vertices by `first_reached`.
. Filter the vertices by the rank attribute to keep the only vertex of rank `n`.
. Aggregate `first_reached` to a scalar on the filtered graph (use either _average_, _first_,
_max_, _min_, or _most_common_ - there is only one vertex in the filtered graph).
. Filter the vertices and edges of the original graph and keep the ones that has smaller or equal
`first_reached` or `first_traversed` values than the value of the derived scalar.

====
[[startpoints]] Number of start points::
The number of times a new start point is selected.

[[walksfromonepoint]] Number of walks from each start point::
The number of times the random walk restarts from the same start point before selecting a new start
point.

[[walkabortionprobability]] Walk abortion probability::
The probability of aborting a walk instead of moving along an edge. Therefore the length of the
parts of the walk between two abortions follows a geometric distribution with parameter _Walk
abortion probability_.

[[vertexattrname]] Save vertex indices as::
The name of the attribute which shows which step reached the given vertex first. It is not defined
on vertices that were never reached.

[[edgeattrname]] Save edge indices as::
The name of the attribute which shows which step traversed the given edge first. It is not defined
on edges that were never traversed.

[[seed]] Seed::
The random seed.
+
include::{g}[tag=random-seed]
====