### Split edges

Split (multiply) edges in a graph. A Double edge attribute controls how many
copies of the edge should exist after the operation. If this attribute is
1, the edge will be kept as it is. If this attribute is zero, the edge
will be discarded entirely. Higher values (e.g., 2) will result in
more identical copies of the given edge.

After the operation, all previous edge attributes will be preserved;
in particular, copies of one edge will have the same values for the previous edge
attributes. A new edge attribute (the so called index attribute) will also be
created so that you can differentiate between copies of the same edge.
If a given edge was multiplied by n times, the n new edges will have n different
index attribute values running from 0 to n-1.

====
[[rep]] Repetition attribute::
A Double edge attribute that specifies how many copies of the edge should
exist after the operation.
(The Double value is rounded to the nearest integer, so 1.8 will mean 2 copies.)

[[idx]] Index attribute name::
The name of the attribute that will contain unique identifiers for the otherwise
identical copies of the edge.
====
