### Train a logistic regression model

Trains a logistic regression model using the graph's vertex attributes. The
algorithm converges when the maximum number of iterations is reached or no
coefficient has changed in the last iteration. The threshold of the model is
chosen to maximize the https://en.wikipedia.org/wiki/F1_score[F-score].

https://en.wikipedia.org/wiki/Logistic_regression[Logistic regression] measures
the relationship between the categorical dependent variable and one or more
independent variables by estimating probabilities using a logistic function.

The current implementation of logistic regression only supports binary classes.
====
[p-name]#Model name#::
The model will be stored as a graph attribute using this name.

[p-label]#Label attribute#::
The vertex attribute for which the model is trained to classify. The attribute should
be binary label of either 0.0 or 1.0.

[p-features]#Feature attributes#::
Attributes to be used as inputs for the training algorithm.

[p-max_iter]#Maximum iterations#::
The maximum number of iterations (>=0).

[p-elastic_net_param]#Elastic net mixing#::
This parameter ("alpha") allows combining L1 and L2 regularization.
At alpha=0 we get L2 regularization and at alpha=1 we get L1.

[p-reg_param]#Regularization#::
The parameter of L1/L2 regularization, depending on how the elastic net mixing parameter is set.

====
