### Train a logistic regression model

Trains a logistic regression model using the graph's vertex attributes. The
algorithm converges when the maximum number of iterations is reached or every
coefficient does not change in the last iteration.

https://en.wikipedia.org/wiki/Logistic_regression[Logistic regression] measures
the relationship between the categorical dependent variable and one or more
independent variables by estimating probabilities using a logistic function.

The current implementation of logistic regression only supports binary classes.
Support for multiclass regression will be added in the future.
====
[[name]] Model name::
The model will be stored as a scalar attribute using this name.

[[label]] Label attribute::
The vertex attribute for which the model is trained to classify. The attribute should
be binary label of either 0.0 or 1.0.

[[features]] Feature attributes::
Attributes to be used as inputs for the training algorithm. The trained model
will have a list of features with the same names and semantics.

[[threshold]] Threshold::
Threshold in binary classification prediction, in range [0, 1]. The classification
prediction is 1.0 if the estimated probability of class label 1.0 is over the threshold.

[[max-iter]] Maximum iterations::
The maximum number of iterations (>=0).

[[seed]] Seed::
The random seed.

====