### Train a k-means clustering model

Trains a k-means clustering model using the graph's vertex attributes. The
algorithm converges when the maximum number of iterations is reached or every
cluster center does not move in the last iteration.

https://en.wikipedia.org/wiki/K-means_clustering[KMeans clustering] aims
to partition _n_ observations into _k_ clusters in which each observation belongs
to the cluster with the nearest mean, serving as a prototype of the cluster.

For best results it may be necessary to scale the features before training the model.
====
[[name]] Model name::
The model will be stored as a scalar attribute using this name.

[[features]] Feature attributes::
Attributes to be used as inputs for the training algorithm. The trained model
will have a list of features with the same names and semantics.

[[k]] K clusters::
The number of clusters to be created.

[[max_iter]] Maximum iterations::
The maximum number of iterations (>=0).

[[seed]] Seed::
The random seed.

====
