### Use table as vertex attributes

Imports vertex attributes for existing vertices from a table. This is
useful when you already have vertices and just want to import one or more attributes.

There are two different use cases for this operation:
- Import using unique vertex attribute values. For example if the vertices represent people
this attribute can be a personal ID. In this case the operation fails in case of duplicate
attribute values (either among vertices or in the table).
- Import using a normal vertex attribute. For example this can be a city of residence (vertices
are people) and we can import census data for those cities for each person. Here the operation
allows duplications of cities among vertices (but not in the lookup table).

====
include::{g}[tag=table-import]

[p-id_attr]#Vertex attribute#::
The String vertex attribute which is used to join with the table's ID column.

[p-id_column]#ID column#::
The ID column name in the table. This should be a String column that uses the values
of the chosen vertex attribute as IDs.

[p-prefix]#Name prefix for the imported vertex attributes#::
Prepend this prefix string to the new vertex attribute names. This can be used to avoid
accidentally overwriting existing attributes.

[p-unique_keys]#Assert unique vertex attribute values#::
Assert that the vertex attribute values have to be unique if set true. The values of the
matching ID column in the table have to be unique in both cases.

[p-if_exists]#What happens if an attribute already exists#::
If the attribute from the table clashes with an existing attribute of the graph,
you can select how to handle this:
- **Merge, prefer the table's version**: Where the table defines new values, those will be used.
  Elsewhere the existing values are kept.
- **Merge, prefer the graph's version**: Where the vertex attribute is already defined, it is left
  unchanged. Elsewhere the value from the table is used.
- **Merge, report error on conflict**: An assertion is made to ensure that the values in the table
  are identical to the values in the graph on vertices where both are defined.
- **Keep the graph's version**: The data in the table is ignored.
- **Use the table's version**: The attribute is deleted from the graph and replaced with
  the attribute imported from the table.
- **Disallow this**: A name conflict is treated as an error.
====
