### Use table as edge attributes

Imports edge attributes for existing edges from a table. This is
useful when you already have edges and just want to import one or more attributes.

There are two different use cases for this operation:
- Import using unique edge attribute values. For example if the edges represent relationships
between people (identified by `src` and `dst` IDs) we can import the number of total calls between
each two people. In this case the operation fails for duplicate attribute values - i.e.
parallel edges.
- Import using a normal edge attribute. For example if each edge represents a call and the location
of the person making the call is an edge attribute (cell tower ID) we can import latitudes and
longitudes for those towers. Here the tower IDs still have to be unique in the lookup table.

====
include::{g}[tag=table-import]

[p-id_attr]#Edge attribute#::
The edge attribute which is used to join with the table's ID column.

[p-id_column]#ID column#::
The ID column name in the table. This should be a String column that uses the values
of the chosen edge attribute as IDs.

[p-prefix]#Name prefix for the imported edge attributes#::
Prepend this prefix string to the new edge attribute names. This can be used to avoid
accidentally overwriting existing attributes.

[p-unique_keys]#Assert unique edge attribute values#::
Assert that the edge attribute values have to be unique if set true. The values of the
matching ID column in the table have to be unique in both cases.

[p-if_exists]#What happens if an attribute already exists#::
If the attribute from the table clashes with an existing attribute of the graph,
you can select how to handle this:
- **Merge, prefer the table's version**: Where the table defines new values, those will be used.
  Elsewhere the existing values are kept.
- **Merge, prefer the graph's version**: Where the table defines new values, those will be used.
  Elsewhere the existing values are kept.
- **Merge, report error on conflict**: An assertion is made to ensure that the values in the table
  are identical to the values in the graph on edges where both are defined.
- **Keep the graph's version**: The data in the table is ignored.
- **Use the table's version**: The attribute is deleted from the graph and replaced with
  the attribute imported from the table.
- **Disallow this**: A name conflict is treated as an error.
====
