### Use table as edge attributes

Imports edge attributes for existing edges from a table. This is
useful when you already have edges and just want to import one or more attributes.

There are two different use cases for this operation:
- Import using unique edge attribute values. For example if the edges represent relationships
between people (identified by `src` and `dst` IDs) we can import the number of total calls between
each two people. In this case the operation fails for duplicate attribute values - i.e.
parallel edges.
- Import using a normal edge attribute. For example if each edge represents a call and the location
of the person making the call is an edge attribute (cell tower ID) we can import latitudes and
longitudes for those towers. Here the tower IDs still have to be unique in the lookup table.

====
include::{g}[tag=table-import]

[[id_attr]] Edge attribute::
The edge attribute which is used to join with the table's ID column.

[[id_column]] ID column::
The ID column name in the table. This should be a String column that uses the values
of the chosen edge attribute as IDs.

[[prefix]] Name prefix for the imported edge attributes::
Prepend this prefix string to the new edge attribute names. This can be used to avoid
accidentally overwriting existing attributes.

[[unique_keys]] Assert unique edge attribute values::
Assert that the edge attribute values have to be unique if set true. The values of the
matching ID column in the table have to be unique in both cases.
====
