### Weighted aggregate on neighbors

Aggregates across the vertices that are connected to each vertex. You can use
the `Aggregate on` parameter to define how exactly this aggregation will take
place: choosing one of the 'edges' settings can result in a neighboring
vertex being taken into account several times (depending on the number of edges between
the vertex and its neighboring vertex); whereas choosing one of the 'neighbors' settings
will result in each neighboring vertex being taken into account once.

For example, it can calculate the average age per kilogram of the friends of each person.

====
[p-prefix]#Generated name prefix#::
Save the aggregated attributes with this prefix.

[p-weight]#Weight#::
The `number` attribute to use as weight.

[p-direction]#Aggregate on#::
 - `incoming edges`: Aggregate across the edges coming in to each vertex.
 - `outgoing edges`: Aggregate across the edges going out of each vertex.
 - `all edges`: Aggregate across all the edges going in or out of each vertex.
 - `symmetric edges`:
   Aggregate across the 'symmetric' edges for each vertex: this means that if you have n edges
   going from A to B and k edges going from B to A, then min(n,k) edges will be
   taken into account for both A and B.
 - `in-neighbors`: For each vertex A, aggregate across those vertices
   that have an outgoing edge to A.
 - `out-neighbors`: For each vertex A, aggregate across those vertices
   that have an incoming edge from A.
 - `all neighbors`: For each vertex A, aggregate across those vertices
   that either have an outgoing edge to or an incoming edge from A.
 - `symmetric neighbors`: For each vertex A, aggregate across those vertices
   that have both an outgoing edge to and an incoming edge from A.

include::{g}[tag=weighted-aggregators]
====
