#!/bin/bash

CLOUDERA_MANAGER=$(basename $CLOUDERA_MANAGER_URL)
CLOUDERA_CDH_PARCEL=$(basename $CLOUDERA_CDH_PARCEL_URL)
CLOUDERA_CDH_PARCEL_SHA1=$(basename $CLOUDERA_CDH_PARCEL_SHA1_URL)
CLOUDERA_MANIFEST=$(basename $CLOUDERA_MANIFEST_URL)
CLOUDERA_VERSION=$(basename $(dirname $CLOUDERA_CDH_PARCEL_URL))

