#! /bin/sh

### BEGIN INIT INFO
# Provides: spark_slave_daemon
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2
# Default-Stop:
# Short-Description: Starts spark slave daemon
# Description:       Starts spark slave daemon
#        Blabla
### END INIT INFO

su - -c "spark-0.9.1/sbin/start-slave.sh `hostname` spark://`hostname | sed -E 's/-[^-]+$/-master/'`:7077" xandrew

# ========================
# To set up spark-slave auto startup, copy this file to /etc/init.d/spark-slave, then run:
# sudo update-rc spark-slave defaults
