#! /bin/sh

### BEGIN INIT INFO
# Provides: spark_master_daemon
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2
# Default-Stop:
# Short-Description: Starts spark master daemon
# Description:       Starts spark master daemon
#        Blabla
### END INIT INFO

su - -c "spark-1.0.1/sbin/start-master.sh" xandrew


# ========================
# To set up spark-master auto startup, copy this file to /etc/init.d/spark-master, then run:
# sudo update-rc spark-master defaults
