// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sphynx.proto

package com.lynxanalytics.biggraph.graph_api.proto;

public final class SphynxOuterClass {
  private SphynxOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CanComputeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sphynx.CanComputeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operation = 1;</code>
     * @return The operation.
     */
    java.lang.String getOperation();
    /**
     * <code>string operation = 1;</code>
     * @return The bytes for operation.
     */
    com.google.protobuf.ByteString
        getOperationBytes();
  }
  /**
   * Protobuf type {@code sphynx.CanComputeRequest}
   */
  public  static final class CanComputeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sphynx.CanComputeRequest)
      CanComputeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CanComputeRequest.newBuilder() to construct.
    private CanComputeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CanComputeRequest() {
      operation_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CanComputeRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CanComputeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              operation_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.class, com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.Builder.class);
    }

    public static final int OPERATION_FIELD_NUMBER = 1;
    private volatile java.lang.Object operation_;
    /**
     * <code>string operation = 1;</code>
     * @return The operation.
     */
    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operation_ = s;
        return s;
      }
    }
    /**
     * <code>string operation = 1;</code>
     * @return The bytes for operation.
     */
    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOperationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operation_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOperationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest)) {
        return super.equals(obj);
      }
      com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest other = (com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest) obj;

      if (!getOperation()
          .equals(other.getOperation())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sphynx.CanComputeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sphynx.CanComputeRequest)
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.class, com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.Builder.class);
      }

      // Construct using com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operation_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeRequest_descriptor;
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest getDefaultInstanceForType() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest build() {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest buildPartial() {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest result = new com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest(this);
        result.operation_ = operation_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest) {
          return mergeFrom((com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest other) {
        if (other == com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest.getDefaultInstance()) return this;
        if (!other.getOperation().isEmpty()) {
          operation_ = other.operation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object operation_ = "";
      /**
       * <code>string operation = 1;</code>
       * @return The operation.
       */
      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operation = 1;</code>
       * @return The bytes for operation.
       */
      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operation = 1;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      /**
       * <code>string operation = 1;</code>
       * @param value The bytes for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operation_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sphynx.CanComputeRequest)
    }

    // @@protoc_insertion_point(class_scope:sphynx.CanComputeRequest)
    private static final com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest();
    }

    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanComputeRequest>
        PARSER = new com.google.protobuf.AbstractParser<CanComputeRequest>() {
      @java.lang.Override
      public CanComputeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CanComputeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CanComputeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CanComputeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CanComputeReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sphynx.CanComputeReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool canCompute = 1;</code>
     * @return The canCompute.
     */
    boolean getCanCompute();
  }
  /**
   * Protobuf type {@code sphynx.CanComputeReply}
   */
  public  static final class CanComputeReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sphynx.CanComputeReply)
      CanComputeReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CanComputeReply.newBuilder() to construct.
    private CanComputeReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CanComputeReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CanComputeReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CanComputeReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              canCompute_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.class, com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.Builder.class);
    }

    public static final int CANCOMPUTE_FIELD_NUMBER = 1;
    private boolean canCompute_;
    /**
     * <code>bool canCompute = 1;</code>
     * @return The canCompute.
     */
    public boolean getCanCompute() {
      return canCompute_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (canCompute_ != false) {
        output.writeBool(1, canCompute_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (canCompute_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, canCompute_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply)) {
        return super.equals(obj);
      }
      com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply other = (com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply) obj;

      if (getCanCompute()
          != other.getCanCompute()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CANCOMPUTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCanCompute());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sphynx.CanComputeReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sphynx.CanComputeReply)
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.class, com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.Builder.class);
      }

      // Construct using com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        canCompute_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.internal_static_sphynx_CanComputeReply_descriptor;
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply getDefaultInstanceForType() {
        return com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply build() {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply buildPartial() {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply result = new com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply(this);
        result.canCompute_ = canCompute_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply) {
          return mergeFrom((com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply other) {
        if (other == com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply.getDefaultInstance()) return this;
        if (other.getCanCompute() != false) {
          setCanCompute(other.getCanCompute());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean canCompute_ ;
      /**
       * <code>bool canCompute = 1;</code>
       * @return The canCompute.
       */
      public boolean getCanCompute() {
        return canCompute_;
      }
      /**
       * <code>bool canCompute = 1;</code>
       * @param value The canCompute to set.
       * @return This builder for chaining.
       */
      public Builder setCanCompute(boolean value) {
        
        canCompute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool canCompute = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCanCompute() {
        
        canCompute_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sphynx.CanComputeReply)
    }

    // @@protoc_insertion_point(class_scope:sphynx.CanComputeReply)
    private static final com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply();
    }

    public static com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanComputeReply>
        PARSER = new com.google.protobuf.AbstractParser<CanComputeReply>() {
      @java.lang.Override
      public CanComputeReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CanComputeReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CanComputeReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CanComputeReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lynxanalytics.biggraph.graph_api.proto.SphynxOuterClass.CanComputeReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sphynx_CanComputeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sphynx_CanComputeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sphynx_CanComputeReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sphynx_CanComputeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sphynx.proto\022\006sphynx\"&\n\021CanComputeRequ" +
      "est\022\021\n\toperation\030\001 \001(\t\"%\n\017CanComputeRepl" +
      "y\022\022\n\ncanCompute\030\001 \001(\0102J\n\006Sphynx\022@\n\nCanCo" +
      "mpute\022\031.sphynx.CanComputeRequest\032\027.sphyn" +
      "x.CanComputeReplyB,\n*com.lynxanalytics.b" +
      "iggraph.graph_api.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sphynx_CanComputeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sphynx_CanComputeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sphynx_CanComputeRequest_descriptor,
        new java.lang.String[] { "Operation", });
    internal_static_sphynx_CanComputeReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sphynx_CanComputeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sphynx_CanComputeReply_descriptor,
        new java.lang.String[] { "CanCompute", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
