---
extends:
- eslint:recommended
- 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
root: true
env:
  es2021: true
  browser: true
  node: true
  es6: true
  commonjs: true
  jest: true
rules:
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  comma-spacing: [error]
  curly: [error]
  dot-location: [error, property]
  eol-last: [error]
  eqeqeq: [error]
  indent: [error, 2]
  keyword-spacing: [error]
  key-spacing: [error]
  linebreak-style: [error, unix]
  no-console: [warn]
  no-debugger: [warn]
  no-unreachable: [warn]
  no-unused-vars: [warn]
  no-multi-spaces: [error]
  no-sequences: [error]
  no-trailing-spaces: [error]
  quotes: [error, single]
  semi: [error, always]
  space-before-blocks: [error]
  space-in-parens: [error]
  space-infix-ops: [error]
  arrow-spacing: [error, {before: true, after: true}]
  no-var: [error]
  no-undef: [error]
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  # "false" means overwriting is disallowed.
  angular: false
